/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PizzaToast {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLPizzaToastElement extends Components.PizzaToast, HTMLStencilElement {
    }
    var HTMLPizzaToastElement: {
        prototype: HTMLPizzaToastElement;
        new (): HTMLPizzaToastElement;
    };
    interface HTMLElementTagNameMap {
        "pizza-toast": HTMLPizzaToastElement;
    }
}
declare namespace LocalJSX {
    interface PizzaToast {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "pizza-toast": PizzaToast;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pizza-toast": LocalJSX.PizzaToast & JSXBase.HTMLAttributes<HTMLPizzaToastElement>;
        }
    }
}
