/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface QuickToast {
        "autoHidden": boolean;
        "closeButtonText": string;
        "hide": () => Promise<void>;
        "noCloseButton": boolean;
        "show": ({ title, message, time }?: {
            title: string;
            message: string;
            time: any;
        }) => Promise<void>;
        "time": number;
    }
}
declare global {
    interface HTMLQuickToastElement extends Components.QuickToast, HTMLStencilElement {
    }
    var HTMLQuickToastElement: {
        prototype: HTMLQuickToastElement;
        new (): HTMLQuickToastElement;
    };
    interface HTMLElementTagNameMap {
        "quick-toast": HTMLQuickToastElement;
    }
}
declare namespace LocalJSX {
    interface QuickToast {
        "autoHidden"?: boolean;
        "closeButtonText"?: string;
        "noCloseButton"?: boolean;
        "time"?: number;
    }
    interface IntrinsicElements {
        "quick-toast": QuickToast;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "quick-toast": LocalJSX.QuickToast & JSXBase.HTMLAttributes<HTMLQuickToastElement>;
        }
    }
}
