/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PizzaToast {
        "hide": () => Promise<void>;
        "show": ({ title, message, time }?: {
            title: string;
            message: string;
            time: any;
        }) => Promise<void>;
        "time": number;
    }
}
declare global {
    interface HTMLPizzaToastElement extends Components.PizzaToast, HTMLStencilElement {
    }
    var HTMLPizzaToastElement: {
        prototype: HTMLPizzaToastElement;
        new (): HTMLPizzaToastElement;
    };
    interface HTMLElementTagNameMap {
        "pizza-toast": HTMLPizzaToastElement;
    }
}
declare namespace LocalJSX {
    interface PizzaToast {
        "time"?: number;
    }
    interface IntrinsicElements {
        "pizza-toast": PizzaToast;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pizza-toast": LocalJSX.PizzaToast & JSXBase.HTMLAttributes<HTMLPizzaToastElement>;
        }
    }
}
